theme: jekyll-theme-minimal
title: リスキリング（プログラミング）
description: 独学プログラミング演習
markdown: GFM
plugins:
  - jekyll-readme-index
readme_index:
enabled:          true
remove_originals: false
with_frontmatter: false
