remote_theme: "mmistakes/minimal-mistakes@4.27.1"
locale: "ja-JP"
title: "リスキリング（プログラミング）"
description: "独学プログラミング演習"
url: https://tatsukiyoshi.github.io
baseurl: ""
plugins:
  - jekyll-include-cache
