remote_theme: "mmistakes/minimal-mistakes"
locale: "ja-JP"
title: "リスキリング（プログラミング）"
description: "独学プログラミング演習"
url: https://tatsukiyoshi.github.io
baseurl: ""
markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
minimal_mistakes_skin: "mint"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
